# Generated by Django 5.0.3 on 2024-06-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fail_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usersearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_box', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'messages',
                'ordering': ['messages_box'],
            },
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
